version: '3'
services:
  web:
    build: .
    ports:
      - "10020:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data  # 데이터베이스 파일 저장용 볼륨
    environment:
      - NODE_ENV=production
    restart: always